// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sayHello.proto

package com.leolian.distributed.architecture.chapter01.grpc.common;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
